name: Run all tests

on:
    # schedule:
    #   - cron: '* 5 * * *'
    #   - cron: '* 20 * * *'
    workflow_dispatch:

jobs:
    test:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                python-version: '3.11'
                cache: 'pip'
            - run: pip install -r requirements.txt
            - name: Run Tests
              run: pytest --alluredir=results tests/
            - name: Upload Allure HTML report as an artifact
              if: always()
              uses: actions/upload-artifact@v3
              with:
                name: allure-html-report
                path: results/
